### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by twratl** [exostack-oss/ShellofACloud#1]
Cannot type any commands into the shell.

**Comment by somoore** [comment]
> Cannot type any commands into the shell
Thanks for reporting this! 

Out of curiosity - when this happens, can you click ‘Disconnect’ and then ‘Connect’ once more.
Are you able to input commands after doing this?

I’ll look into this further - thanks!

**Comment by twratl** [comment]
Confirmed. After disconnecting and connecting again I was able to input commands into the shell.
